name: Python CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ${{ matrix.os }}  # crates a matrix that includes multiple operating systems to run on
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.10]


    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r fairsharerFile/requirements.txt
    - name: Lint with Ruff
      run: |
        ruff check .
    - name: Test with pytest
      run: |
        pytest
